spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

jwt:
  private:
    key: classpath:rsa.privatekey
  public:
    key: classpath:rsa.publickey
  expiry: 36000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE